### ISSUE TITLE
Wireflow Feedback

### ISSUE THREAD

**Issue by zenitba** [yujing-student/fix-the-flow-interactive-website#4]
**Tip**
Kleur de zoek button bij een active state
Schrijf de userstory erbij

**Tops**
De wireflow zit er goed uit mooi dat je de beschrijving erbij hebt geschreven.

**Comment by yujing-student** [comment]
![IMG_8474](https://github.com/yujing-student/fix-the-flow-interactive-website/assets/100352887/836c5c39-0282-4325-b198-cdb4fcface12)
dit heb ik gedaan
