### ISSUE TITLE
User test - Ajajx

### ISSUE THREAD

**Issue by Nazneen05x** [yujing-student/fix-the-flow-interactive-website#8]
**Taak/scenario:**

Je hebt je taak en scenario goed (duidelijk) beschreven, ik wist gelijk wat ik moest doen. 

**Feedback Website  (test):**

Het beste zou zijn als je naar een boek zoekt in de zoekfunctie en op enter klikt, dat je dan alle boeken gelijk tevoorschijn komen. In plaats van naar beneden scrollen om de boeken te bekijken. Verder is alles duidelijk.

**Comment by yujing-student** [comment]
dit heb ik toegepast in de zoekfunctie zodat de gebruiker direct de boeken te zien krijgt zie de link naar de code :https://github.com/yujing-student/fix-the-flow-interactive-website/blob/6d599440e06b11264f1ed6df03896480026dd0c0/scripts/script-enterkey2.js#L82-L97
